name: CI workflow

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit test with nose
        run: nosetests
        env:   
          DATABASE_URL: "redis://redis:6379"

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          version: "v0.1.13"